[build]
provider = "python"

[phases]
build = [
    "pip install -r backend/requirements.txt",
    "cd frontend && npm install && npm run build"
]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT && cd frontend && npm start"
