[build]
provider = "python"

[phases]
build = [
    "pip install -r backend/requirements.txt",
    "cd frontend && npm install",
    "cd frontend && npm run build"
]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"

[static]
directory = "frontend/build"
