[build]
provider = "python"
python_version = "3.9"

[phases]
install = [
    "python -m pip install --upgrade pip",
    "pip install -r backend/requirements.txt"
]

build = [
    "cd frontend && npm install",
    "cd frontend && npm run build"
]

[start]
command = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"

[static]
directory = "frontend/build"
